<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>default</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EasyConsole.Netstandard"  />
    <PackageReference Include="Lamar.Microsoft.DependencyInjection"  />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder"  />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables"  />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json"  />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"  />
    <PackageReference Include="Microsoft.Extensions.Hosting"  />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd"  />
    <PackageReference Include="Newtonsoft.Json"  />
    <PackageReference Include="runtime.unix.System.Runtime.Extensions"  />
    <PackageReference Include="Swashbuckle.AspNetCore"  />
    <PackageReference Include="System.IO.Ports"  />
  </ItemGroup>
  <ItemGroup>
    <None Remove="appconfig.HelloNetCoreGtw.json" />
    <None Remove="nlog.config" />
    <None Remove="appconfig.DESKTOP-1H8BLHA.json" />
    <None Remove="appconfig.json" />
    <None Remove="libnserial.so.1" />
    <None Remove="nlog-internal.log" />
    <None Remove="2018-09-26.log" />
  </ItemGroup>
  <ItemGroup>
    <None Include="nlog.config" CopyToOutputDirectory="Always" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HelloHome.Central.Common.IoC\HelloHome.Central.Common.IoC.csproj" />
    <ProjectReference Include="..\HelloHome.Central.Common\HelloHome.Central.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appconfig.MacBook-Pro.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appconfig.HelloNetCoreGtw.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="NodeBridge\Performance\" />
  </ItemGroup>
  <ProjectExtensions>
    <VisualStudio>
      <UserProperties />
    </VisualStudio>
  </ProjectExtensions>
</Project>