name: hh-Central
services:
  db:
    image: mariadb:latest
    container_name: hh-db
    ports:
      - "3306:3306"
    volumes:
      - hhdb-data:/var/lib/mysql:Z
    environment:
      MARIADB_ROOT_PASSWORD: mariapass
      MARIADB_DATABASE: hhdev
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: hh-mqtt
    ports:
      - "1883:1883"
      - "8082:8080"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  seq:
    image: datalust/seq:latest
    container_name: hh-seq
    ports:
      - "5341:5381"
      - "8081:80"
    volumes:
      - hhseq-data:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=seqpass
  core:
    container_name: hh-core
    depends_on:
      - db
      - mqtt-broker
    platform: linux/arm64
    build:      
      context: ../../HelloHomeCentral
      dockerfile: HelloHome.Central.Core/Dockerfile
  api:
    container_name: hh-api
    platform: linux/arm64
    build:      
      context: ../../HelloHomeCentral
      dockerfile: HelloHome.Central.API/Dockerfile
    ports:
    - "8080:8080"
  simulator:
    container_name: hh-simulator
    platform: linux/arm64
    build:      
      context: ../../HelloHomeCentral
      dockerfile: HelloHome.Central.Simulator/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=/api
    volumes:
      - ../HelloHome.Central.Simulator:/app
      - hhsim-npm:/app/node_modules
    depends_on:
      - api
volumes:
  hhdb-data:
  hhsim-npm:
  hhseq-data: