language: csharp
mono: none
dotnet: 2.1.3
install:
 - dotnet restore
script:
 - dotnet build
 - dotnet test HelloHome.Central.Tests/HelloHome.Central.Tests.csproj
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: HelloHome.Central.Hub/bin/Debug/netcoreapp2.0/*
  skip_cleanup: true
  on:
    tags: true
