language: csharp
mono: none
dotnet: 2.1.3
install:
 - dotnet restore
script:
 - shash=$(echo ${TRAVIS_COMMIT} | cut -c 1-7)
 #- dotnet build --version-suffix ${shash}
 - dotnet test HelloHome.Central.Tests/HelloHome.Central.Tests.csproj --filter skip!=ci
before_deploy:
 - dotnet publish HelloHome.Central.Hub/HelloHome.Central.Hub.csproj --version-suffix ${shash} -r linux-arm
 - cd ${TRAVIS_BUILD_DIR}/HelloHome.Central.Hub/bin/Debug/netcoreapp2.0/linux-arm/publish/
 - echo ${TRAVIS_COMMIT} > version.txt
 - tar -zcf HelloHome.Central-${TRAVIS_TAG}-${TRAVIS_COMMIT}-${TRAVIS_BUILD_NUMBER}.tar.gz *.*
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: ${TRAVIS_BUILD_DIR}/HelloHome.Central.Hub/bin/Debug/netcoreapp2.0/linux-arm/publish/HelloHome.Central-${TRAVIS_TAG}-${TRAVIS_COMMIT}-${TRAVIS_BUILD_NUMBER}.tar.gz
  skip_cleanup: true
  on:
    tags: true
