<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\HelloHome.Central.Common\HelloHome.Central.Common.csproj" />
      <ProjectReference Include="..\HelloHome.Central.Domain\HelloHome.Central.Domain.csproj" />
    </ItemGroup>

</Project>
