// <auto-generated />
using System;
using HelloHome.Central.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelloHome.Central.Repository.Migrations
{
    [DbContext(typeof(HhDbContext))]
    [Migration("20231209094622_UniqueIndexOnPortNameNodeId")]
    partial class UniqueIndexOnPortNameNodeId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("TriggerId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("TriggerId");

                    b.ToTable("Action", (string)null);

                    b.HasDiscriminator<string>("Type").HasValue("Action");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Condition", (string)null);

                    b.HasDiscriminator<string>("Type").HasValue("Condition");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.EnergyMeterSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Discr")
                        .HasColumnType("int");

                    b.Property<double>("Snapshot")
                        .HasColumnType("double");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("EnergyMeterSnapshot", (string)null);

                    b.HasDiscriminator<int>("Discr");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Identifier")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RfAddress")
                        .HasColumnType("int");

                    b.Property<long>("Signature")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("RfAddress")
                        .IsUnique();

                    b.ToTable("Node", (string)null);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.NodeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("nodelog", (string)null);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.Port", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("NodeId")
                        .HasColumnType("int");

                    b.Property<byte>("PortNumber")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NodeId", "Name")
                        .IsUnique();

                    b.ToTable("Port", (string)null);

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.PortHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Discr")
                        .HasColumnType("int");

                    b.Property<int>("PortId")
                        .HasColumnType("int");

                    b.Property<int>("Rssi")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("PortHistory", (string)null);

                    b.HasDiscriminator<int>("Discr");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.Script", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("OnFinnishId")
                        .HasColumnType("int");

                    b.Property<int>("TriggerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OnFinnishId");

                    b.HasIndex("TriggerId");

                    b.ToTable("Script", (string)null);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.ScriptAction", b =>
                {
                    b.Property<int>("ScriptId")
                        .HasColumnType("int");

                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("ScriptId", "ActionId");

                    b.HasIndex("ActionId");

                    b.ToTable("ScriptAction", (string)null);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.ScriptCondition", b =>
                {
                    b.Property<int>("ScriptId")
                        .HasColumnType("int");

                    b.Property<int>("ConditionId")
                        .HasColumnType("int");

                    b.HasKey("ScriptId", "ConditionId");

                    b.HasIndex("ConditionId");

                    b.ToTable("ScriptCondition", (string)null);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.Trigger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Trigger", (string)null);

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.ActuatorAction", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.Action");

                    b.Property<int?>("ActuatorId")
                        .HasColumnType("int");

                    b.HasIndex("ActuatorId");

                    b.HasDiscriminator().HasValue("AA");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.ScheduleAction", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.Action");

                    b.Property<TimeSpan>("Delay")
                        .HasColumnType("time(6)");

                    b.Property<int?>("ScheduledActionId")
                        .HasColumnType("int");

                    b.HasIndex("ScheduledActionId");

                    b.HasDiscriminator().HasValue("SC");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.PortBasedCondition<HelloHome.Central.Domain.Entities.EnvironmentSensor>", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.Condition");

                    b.Property<int>("PortId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("PortId");

                    b.HasIndex("PortId");

                    b.HasDiscriminator().HasValue("PortBasedCondition<EnvironmentSensor>");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.PortBasedCondition<HelloHome.Central.Domain.Entities.RelayActuator>", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.Condition");

                    b.Property<int>("PortId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("PortId");

                    b.HasIndex("PortId");

                    b.HasDiscriminator().HasValue("PortBasedCondition<RelayActuator>");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.PortBasedCondition<HelloHome.Central.Domain.Entities.SwitchSensor>", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.Condition");

                    b.Property<int>("PortId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("PortId");

                    b.HasIndex("PortId");

                    b.HasDiscriminator().HasValue("PortBasedCondition<SwitchSensor>");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.TimeOfTheDayCondition", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.Condition");

                    b.Property<TimeSpan>("From")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("To")
                        .HasColumnType("time(6)");

                    b.HasDiscriminator().HasValue("TimeOfTheDayCondition");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.PulseEnergyMeterSnapshot", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.EnergyMeterSnapshot");

                    b.Property<int?>("PortId")
                        .HasColumnType("int");

                    b.Property<int>("PulseCount")
                        .HasColumnType("int");

                    b.HasIndex("PortId");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.ActuatorPort", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.Port");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.LoggerPort", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.Port");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.SensorPort", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.Port");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.EnvironmentHistory", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.PortHistory");

                    b.Property<float?>("Humidity")
                        .HasColumnType("float");

                    b.Property<float?>("Pressure")
                        .HasColumnType("float");

                    b.Property<float?>("Temperature")
                        .HasColumnType("float");

                    b.HasIndex("PortId");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.FloatLoggerHistory", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.PortHistory");

                    b.Property<float>("Data")
                        .HasColumnType("float")
                        .HasColumnName("FloatLogData");

                    b.HasIndex("PortId");

                    b.HasDiscriminator().HasValue(8);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.IntLoggerHistory", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.PortHistory");

                    b.Property<int>("Data")
                        .HasColumnType("int")
                        .HasColumnName("IntLogData");

                    b.HasIndex("PortId");

                    b.HasDiscriminator().HasValue(7);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.NodeHealthHistory", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.PortHistory");

                    b.Property<int>("SendErrorCount")
                        .HasColumnType("int");

                    b.Property<float?>("VIn")
                        .HasColumnType("float");

                    b.HasIndex("PortId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.PulseHistory", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.PortHistory");

                    b.Property<bool>("IsOffset")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NewPulses")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasIndex("PortId");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.PushButtonHistory", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.PortHistory");

                    b.Property<int>("PressStyle")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("NewSensorState");

                    b.HasIndex("PortId");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.RelayHistory", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.PortHistory");

                    b.Property<int>("NewRelayState")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("NewSensorState");

                    b.HasIndex("PortId");

                    b.HasDiscriminator().HasValue(9);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.SwitchHistory", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.PortHistory");

                    b.Property<int>("NewSensorState")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("NewSensorState");

                    b.HasIndex("PortId");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.VarioHistory", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.PortHistory");

                    b.Property<int>("NewLevel")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("NewSensorState");

                    b.HasIndex("PortId");

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.CronTrigger", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.Trigger");

                    b.Property<string>("CronExpression")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.SensorTrigger", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.Trigger");

                    b.Property<int>("SensorPortId")
                        .HasColumnType("int");

                    b.HasIndex("SensorPortId");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.RelayAction", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.ActuatorAction");

                    b.HasDiscriminator().HasValue("RA");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.TemperatureWithinRangeCondition", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.PortBasedCondition<HelloHome.Central.Domain.Entities.EnvironmentSensor>");

                    b.Property<float>("MaxTemperature")
                        .HasColumnType("float");

                    b.Property<float>("MinTemperature")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("TemperatureWithinRangeCondition");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.RelayOffCondition", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.PortBasedCondition<HelloHome.Central.Domain.Entities.RelayActuator>");

                    b.HasDiscriminator().HasValue("RF");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.RelayOnCondition", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.PortBasedCondition<HelloHome.Central.Domain.Entities.RelayActuator>");

                    b.HasDiscriminator().HasValue("RN");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.SwitchOffCondition", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.PortBasedCondition<HelloHome.Central.Domain.Entities.SwitchSensor>");

                    b.HasDiscriminator().HasValue("TD");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.SwitchOnCondition", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.PortBasedCondition<HelloHome.Central.Domain.Entities.SwitchSensor>");

                    b.HasDiscriminator().HasValue("SN");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.RelayActuator", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.ActuatorPort");

                    b.Property<int>("RelayState")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("PortState");

                    b.HasDiscriminator().HasValue(7);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.FloatLogger", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.LoggerPort");

                    b.Property<float>("Data")
                        .HasColumnType("float")
                        .HasColumnName("FloatLogData");

                    b.HasDiscriminator().HasValue(8);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.IntLogger", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.LoggerPort");

                    b.Property<int>("Data")
                        .HasColumnType("int")
                        .HasColumnName("IntLogData");

                    b.HasDiscriminator().HasValue(9);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.EnvironmentSensor", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.SensorPort");

                    b.Property<float>("AtmPressure")
                        .HasColumnType("float");

                    b.Property<float>("Humidity")
                        .HasColumnType("float");

                    b.Property<float>("Temperature")
                        .HasColumnType("float");

                    b.Property<int>("UpdateFrequency")
                        .HasColumnType("int")
                        .HasColumnName("EnvUpdateFreq");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.NodeHealthSensor", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.SensorPort");

                    b.Property<int>("SendError")
                        .HasColumnType("int");

                    b.Property<int>("UpdateFrequency")
                        .HasColumnType("int")
                        .HasColumnName("HealtUpdateFreq");

                    b.Property<float>("VIn")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.PulseSensor", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.SensorPort");

                    b.Property<int>("PulseCount")
                        .HasColumnType("int");

                    b.Property<double?>("PulsePerUnitRatio")
                        .HasColumnType("double");

                    b.Property<int?>("Unit")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.PushButtonSensor", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.SensorPort");

                    b.Property<int>("LastPressStyle")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("PortState");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.SwitchSensor", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.SensorPort");

                    b.Property<int>("SwitchState")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("PortState");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.VarioSensor", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.SensorPort");

                    b.Property<int>("Level")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("PortState");

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.PushTrigger", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.SensorTrigger");

                    b.Property<int?>("PressStyle")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.SwitchTrigger", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.SensorTrigger");

                    b.Property<bool?>("TriggerOnState")
                        .HasColumnType("tinyint(1)");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.VarioTrigger", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.SensorTrigger");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.TurnOffAction", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.RelayAction");

                    b.HasDiscriminator().HasValue("TF");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.TurnOnAction", b =>
                {
                    b.HasBaseType("HelloHome.Central.Domain.Entities.RelayAction");

                    b.HasDiscriminator().HasValue("TN");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.Action", b =>
                {
                    b.HasOne("HelloHome.Central.Domain.Entities.Trigger", "Trigger")
                        .WithMany("Actions")
                        .HasForeignKey("TriggerId");

                    b.Navigation("Trigger");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.Node", b =>
                {
                    b.OwnsOne("HelloHome.Central.Domain.Entities.NodeAggregatedData", "AggregatedData", b1 =>
                        {
                            b1.Property<int>("NodeId")
                                .HasColumnType("int");

                            b1.Property<float?>("AtmosphericPressure")
                                .HasColumnType("float");

                            b1.Property<float?>("Humidity")
                                .HasColumnType("float");

                            b1.Property<float>("MaxUpTimeRaw")
                                .HasColumnType("float");

                            b1.Property<int>("NodeStartCount")
                                .HasColumnType("int");

                            b1.Property<int>("Rssi")
                                .HasColumnType("int");

                            b1.Property<int>("SendErrorCount")
                                .HasColumnType("int");

                            b1.Property<DateTime>("StartupTime")
                                .HasColumnType("datetime(6)");

                            b1.Property<float?>("Temperature")
                                .HasColumnType("float");

                            b1.Property<float?>("VIn")
                                .HasColumnType("float");

                            b1.HasKey("NodeId");

                            b1.ToTable("Node");

                            b1.WithOwner("Node")
                                .HasForeignKey("NodeId");

                            b1.Navigation("Node");
                        });

                    b.OwnsOne("HelloHome.Central.Domain.Entities.NodeMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("NodeId")
                                .HasColumnType("int");

                            b1.Property<short>("ExtraFeatures")
                                .HasColumnType("smallint");

                            b1.Property<string>("Name")
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("Name");

                            b1.Property<int>("NodeType")
                                .HasColumnType("int");

                            b1.Property<string>("Version")
                                .HasMaxLength(10)
                                .HasColumnType("varchar(10)")
                                .HasColumnName("Version");

                            b1.HasKey("NodeId");

                            b1.ToTable("Node");

                            b1.WithOwner("Node")
                                .HasForeignKey("NodeId");

                            b1.Navigation("Node");
                        });

                    b.Navigation("AggregatedData");

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.NodeLog", b =>
                {
                    b.HasOne("HelloHome.Central.Domain.Entities.Node", null)
                        .WithMany("Logs")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.Port", b =>
                {
                    b.HasOne("HelloHome.Central.Domain.Entities.Node", "Node")
                        .WithMany("Ports")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.Script", b =>
                {
                    b.HasOne("HelloHome.Central.Domain.Entities.Script", "OnFinnish")
                        .WithMany()
                        .HasForeignKey("OnFinnishId");

                    b.HasOne("HelloHome.Central.Domain.Entities.Trigger", "Trigger")
                        .WithMany("Scripts")
                        .HasForeignKey("TriggerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OnFinnish");

                    b.Navigation("Trigger");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.ScriptAction", b =>
                {
                    b.HasOne("HelloHome.Central.Domain.Entities.Action", "Action")
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelloHome.Central.Domain.Entities.Script", "Script")
                        .WithMany("Actions")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Script");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.ScriptCondition", b =>
                {
                    b.HasOne("HelloHome.Central.Domain.Entities.Condition", "Condition")
                        .WithMany()
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelloHome.Central.Domain.Entities.Script", "Script")
                        .WithMany("Conditions")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condition");

                    b.Navigation("Script");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.ActuatorAction", b =>
                {
                    b.HasOne("HelloHome.Central.Domain.Entities.ActuatorPort", "Actuator")
                        .WithMany()
                        .HasForeignKey("ActuatorId");

                    b.Navigation("Actuator");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.ScheduleAction", b =>
                {
                    b.HasOne("HelloHome.Central.Domain.Entities.Action", "ScheduledAction")
                        .WithMany()
                        .HasForeignKey("ScheduledActionId");

                    b.Navigation("ScheduledAction");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.PortBasedCondition<HelloHome.Central.Domain.Entities.EnvironmentSensor>", b =>
                {
                    b.HasOne("HelloHome.Central.Domain.Entities.EnvironmentSensor", "Port")
                        .WithMany()
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Condition_Port_PortId");

                    b.Navigation("Port");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.PortBasedCondition<HelloHome.Central.Domain.Entities.RelayActuator>", b =>
                {
                    b.HasOne("HelloHome.Central.Domain.Entities.RelayActuator", "Port")
                        .WithMany()
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Condition_Port_PortId");

                    b.Navigation("Port");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.PortBasedCondition<HelloHome.Central.Domain.Entities.SwitchSensor>", b =>
                {
                    b.HasOne("HelloHome.Central.Domain.Entities.SwitchSensor", "Port")
                        .WithMany()
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Condition_Port_PortId");

                    b.Navigation("Port");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.PulseEnergyMeterSnapshot", b =>
                {
                    b.HasOne("HelloHome.Central.Domain.Entities.PulseSensor", "Port")
                        .WithMany()
                        .HasForeignKey("PortId");

                    b.Navigation("Port");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.EnvironmentHistory", b =>
                {
                    b.HasOne("HelloHome.Central.Domain.Entities.EnvironmentSensor", "Port")
                        .WithMany("History")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Port_PortHistory_PortId");

                    b.Navigation("Port");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.FloatLoggerHistory", b =>
                {
                    b.HasOne("HelloHome.Central.Domain.Entities.FloatLogger", "Port")
                        .WithMany("History")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Port_PortHistory_PortId");

                    b.Navigation("Port");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.IntLoggerHistory", b =>
                {
                    b.HasOne("HelloHome.Central.Domain.Entities.IntLogger", "Port")
                        .WithMany("History")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Port_PortHistory_PortId");

                    b.Navigation("Port");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.NodeHealthHistory", b =>
                {
                    b.HasOne("HelloHome.Central.Domain.Entities.NodeHealthSensor", "Port")
                        .WithMany("History")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Port_PortHistory_PortId");

                    b.Navigation("Port");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.PulseHistory", b =>
                {
                    b.HasOne("HelloHome.Central.Domain.Entities.PulseSensor", "Port")
                        .WithMany("History")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Port_PortHistory_PortId");

                    b.Navigation("Port");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.PushButtonHistory", b =>
                {
                    b.HasOne("HelloHome.Central.Domain.Entities.PushButtonSensor", "Port")
                        .WithMany("History")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Port_PortHistory_PortId");

                    b.Navigation("Port");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.RelayHistory", b =>
                {
                    b.HasOne("HelloHome.Central.Domain.Entities.RelayActuator", "Port")
                        .WithMany("History")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Port_PortHistory_PortId");

                    b.Navigation("Port");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.SwitchHistory", b =>
                {
                    b.HasOne("HelloHome.Central.Domain.Entities.SwitchSensor", "Port")
                        .WithMany("History")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Port_PortHistory_PortId");

                    b.Navigation("Port");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.VarioHistory", b =>
                {
                    b.HasOne("HelloHome.Central.Domain.Entities.VarioSensor", "Port")
                        .WithMany("History")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Port_PortHistory_PortId");

                    b.Navigation("Port");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.SensorTrigger", b =>
                {
                    b.HasOne("HelloHome.Central.Domain.Entities.SensorPort", "SensorPort")
                        .WithMany("Triggers")
                        .HasForeignKey("SensorPortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SensorPort");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.Node", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Ports");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.Script", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.Trigger", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Scripts");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.SensorPort", b =>
                {
                    b.Navigation("Triggers");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.RelayActuator", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.FloatLogger", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.IntLogger", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.EnvironmentSensor", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.NodeHealthSensor", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.PulseSensor", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.PushButtonSensor", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.SwitchSensor", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("HelloHome.Central.Domain.Entities.VarioSensor", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
